#!/usr/bin/env node

/**
 * Module dependencies.
 */

var https_app = require('./https_app');
var http_app = require('./http_app');
var debug = require('debug')('nucleotid:server');
var http = require('http');
var https = require('https');
var fs = require('fs');

/*
** Create HTTP server.
*/

var http_port = normalizePort(process.env.HTTP_PORT || '80');
http_app.set('port', http_port);
var http_server = http.createServer(http_app);

http_server.listen(http_port);
http_server.on('error', onError);
http_server.on('listening', onListening);

/*
** Create HTTPS server.
*/

var https_port = normalizePort(process.env.HTTPS_PORT || '443');
https_app.set('port', https_port);

const ssl_options = {
  key: fs.readFileSync('info/nucleotid-dev.key'),
  cert: fs.readFileSync('info/nucleotid-dev.crt')
};

var server = https.createServer(ssl_options,https_app);

/*
** Listen on provided port, on all network interfaces.
*/

server.listen(https_port);
server.on('error', onError);
server.on('listening', onListening);

/**
 * Normalize a port into a number, string, or false.
 */

function normalizePort(val) {
  var port = parseInt(val, 10);

  if (isNaN(port)) {
    // named pipe
    return val;
  }

  if (port >= 0) {
    // port number
    return port;
  }

  return false;
}

/**
 * Event listener for HTTP server "error" event.
 */

function onError(error) {
  if (error.syscall !== 'listen') {
    throw error;
  }

  var bind = typeof port === 'string'
    ? 'Pipe ' + port
    : 'Port ' + port;

  // handle specific listen errors with friendly messages
  switch (error.code) {
    case 'EACCES':
      console.error(bind + ' requires elevated privileges');
      process.exit(1);
      break;
    case 'EADDRINUSE':
      console.error(bind + ' is already in use');
      process.exit(1);
      break;
    default:
      throw error;
  }
}

/**
 * Event listener for HTTP server "listening" event.
 */

function onListening() {
  var addr = server.address();
  var bind = typeof addr === 'string'
    ? 'pipe ' + addr
    : 'port ' + addr.port;
  debug('Listening on ' + bind);
}
